name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.0

      - name: Install Go
        uses: actions/setup-go@v6.5.0
        with:
          go-version-file: go.mod
          cache: true

      - name: Check for vulnerabilities
        run: go run golang.org/x/vuln/cmd/govulncheck@latest ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.3.0
        with:
          version: v2.7.2

      - name: Build and Test
        run: make
